# Generated by Django 6.1.1 on 2026-09-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Datei')),
                ('media_type', models.CharField(choices=[('image', 'Bild'), ('document', 'Dokument'), ('other', 'Sonstige Datei')], default='image', max_length=20, verbose_name='Medientyp')),
                ('alt_text', models.CharField(blank=True, help_text='Für Bilder: kurze inhaltliche Beschreibung für Barrierefreiheit und SEO.', max_length=300, verbose_name='Alternativtext')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Bildunterschrift')),
                ('copyright_notice', models.CharField(blank=True, max_length=300, verbose_name='Copyright / Quelle')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Breite')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Höhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
            ],
            options={
                'verbose_name': 'Medium',
                'verbose_name_plural': 'Medien',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('identifier', models.SlugField(help_text='Zum Beispiel main oder footer.', unique=True, verbose_name='Kennung')),
            ],
            options={
                'verbose_name': 'Navigation',
                'verbose_name_plural': 'Navigationen',
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(help_text='Zum Beispiel /alte-wordpress-seite/', max_length=500, unique=True, verbose_name='Alter Pfad')),
                ('target_path', models.CharField(max_length=500, verbose_name='Neuer Pfad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
            ],
            options={
                'verbose_name': 'Weiterleitung',
                'verbose_name_plural': 'Weiterleitungen',
                'ordering': ['source_path'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('teaser', models.TextField(blank=True, verbose_name='Teaser')),
                ('content', models.TextField(blank=True, verbose_name='Inhalt')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategorie')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Autor')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta-Titel')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta-Beschreibung')),
                ('robots_index', models.BooleanField(default=True, verbose_name='Indexierung erlauben')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='Links folgen erlauben')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('teaser_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_articles', to='cms.mediaasset', verbose_name='Teaserbild')),
            ],
            options={
                'verbose_name': 'Wissensartikel',
                'verbose_name_plural': 'Wissensartikel',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('template_type', models.CharField(choices=[('standard', 'Standardseite'), ('landing', 'Landingpage')], default='standard', max_length=30, verbose_name='Seitentyp')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta-Titel')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('robots_index', models.BooleanField(default=True, verbose_name='Indexierung erlauben')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='Links folgen erlauben')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='cms.page', verbose_name='Übergeordnete Seite')),
            ],
            options={
                'verbose_name': 'Seite',
                'verbose_name_plural': 'Seiten',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('external_url', models.URLField(blank=True, verbose_name='Externe URL')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Sichtbar')),
                ('navigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cms.navigation', verbose_name='Navigation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.navigationitem', verbose_name='Übergeordneter Menüpunkt')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_items', to='cms.page', verbose_name='Interne Seite')),
            ],
            options={
                'verbose_name': 'Navigationspunkt',
                'verbose_name_plural': 'Navigationspunkte',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Text'), ('image_text', 'Bild + Text'), ('features', 'Features / Spalten'), ('cta', 'Call-to-Action'), ('faq', 'FAQ'), ('reference', 'Referenz'), ('form', 'Formular'), ('ci_module', 'CI-Machine-Modul')], max_length=30, verbose_name='Blocktyp')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Strukturierte Inhalte des jeweiligen Blocktyps.', verbose_name='Blockdaten')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_blocks', to='cms.mediaasset', verbose_name='Medium')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='cms.page', verbose_name='Seite')),
            ],
            options={
                'verbose_name': 'Seitenblock',
                'verbose_name_plural': 'Seitenblöcke',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(fields=('parent', 'slug'), name='unique_page_slug_per_parent'),
        ),
    ]
