# Generated by Django 6.1.1 on 2026-09-15 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Zum Beispiel de, en, fr oder es.', max_length=10, unique=True, verbose_name='Sprachcode')),
                ('name', models.CharField(help_text='Deutsche Bezeichnung der Sprache, zum Beispiel Englisch.', max_length=100, verbose_name='Name')),
                ('native_name', models.CharField(help_text='Bezeichnung in der jeweiligen Sprache, zum Beispiel English.', max_length=100, verbose_name='Eigenbezeichnung')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Sprache',
                'verbose_name_plural': 'Sprachen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('domain', models.CharField(help_text='Domain ohne Protokoll und Pfad, zum Beispiel holzerprompt.de.', max_length=255, unique=True, verbose_name='Domain')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
            ],
            options={
                'verbose_name': 'Website',
                'verbose_name_plural': 'Websites',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='Standardsprache')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('url_prefix', models.SlugField(blank=True, help_text='Leer für die Standardsprache; für weitere Sprachen zum Beispiel fr oder es.', max_length=20, verbose_name='URL-Präfix')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Position')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='site_languages', to='cms.language', verbose_name='Sprache')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_languages', to='cms.site', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Website-Sprache',
                'verbose_name_plural': 'Website-Sprachen',
                'ordering': ['site__name', 'position', 'language__name'],
                'constraints': [models.UniqueConstraint(fields=('site', 'language'), name='unique_language_per_site'), models.UniqueConstraint(fields=('site', 'url_prefix'), name='unique_url_prefix_per_site'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('site',), name='unique_default_language_per_site')],
            },
        ),
    ]
