# Generated by Django 6.1.1 on 2026-09-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_language_site_sitelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='internal_name',
            field=models.CharField(default='', help_text='Dient ausschließlich zur Identifikation und Strukturierung der Seite im CMS. Wird nicht auf der Website ausgegeben und nicht übersetzt.', max_length=200, verbose_name='Interne Bezeichnung'),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('slug', models.SlugField(max_length=200, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht')], default='draft', max_length=20, verbose_name='Status')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta-Titel')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='Meta-Beschreibung')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('robots_index', models.BooleanField(default=True, verbose_name='Indexierung erlauben')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='Links folgen erlauben')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Veröffentlicht am')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.page', verbose_name='Seite')),
                ('site_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_translations', to='cms.sitelanguage', verbose_name='Website-Sprache')),
            ],
            options={
                'verbose_name': 'Seitenübersetzung',
                'verbose_name_plural': 'Seitenübersetzungen',
                'ordering': ['site_language', 'title'],
                'constraints': [models.UniqueConstraint(fields=('page', 'site_language'), name='unique_page_translation_per_site_language'), models.UniqueConstraint(fields=('site_language', 'slug'), name='unique_page_translation_slug_per_site_language')],
            },
        ),
    ]
