# Generated by Django 6.1.1 on 2026-09-16 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_page_internal_name_pagetranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlockTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Sprachabhängige Inhalte des Blocks. Die erlaubten Felder werden durch den jeweiligen Blocktyp bestimmt.', verbose_name='Übersetzte Blockinhalte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('page_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.pageblock', verbose_name='Seitenblock')),
                ('site_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_block_translations', to='cms.sitelanguage', verbose_name='Website-Sprache')),
            ],
            options={
                'verbose_name': 'Seitenblock-Übersetzung',
                'verbose_name_plural': 'Seitenblock-Übersetzungen',
                'ordering': ['page_block', 'site_language'],
                'constraints': [models.UniqueConstraint(fields=('page_block', 'site_language'), name='unique_page_block_translation_per_site_language')],
            },
        ),
    ]
