# Generated by Django 6.1.1 on 2026-09-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_pageblocktranslation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['internal_name'], 'verbose_name': 'Seite', 'verbose_name_plural': 'Seiten'},
        ),
        migrations.RemoveConstraint(
            model_name='page',
            name='unique_page_slug_per_parent',
        ),
        migrations.RemoveField(
            model_name='page',
            name='canonical_url',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='page',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='page',
            name='robots_follow',
        ),
        migrations.RemoveField(
            model_name='page',
            name='robots_index',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='page',
            name='status',
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
