# Generated by Django 6.1.1 on 2026-09-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_page_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAssetTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titel')),
                ('alt_text', models.CharField(blank=True, help_text='Für Bilder: kurze inhaltliche Beschreibung für Barrierefreiheit und SEO.', max_length=300, verbose_name='Alternativtext')),
                ('caption', models.CharField(blank=True, max_length=500, verbose_name='Bildunterschrift')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
                ('media_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cms.mediaasset', verbose_name='Medium')),
                ('site_language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_asset_translations', to='cms.sitelanguage', verbose_name='Website-Sprache')),
            ],
            options={
                'verbose_name': 'Medienübersetzung',
                'verbose_name_plural': 'Medienübersetzungen',
                'ordering': ['media_asset', 'site_language'],
                'constraints': [models.UniqueConstraint(fields=('media_asset', 'site_language'), name='unique_media_asset_translation_per_site_language')],
            },
        ),
    ]
