# Generated by Django 6.1.1 on 2026-09-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_mediaassettranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaasset',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='title',
        ),
    ]
