# Generated by Django 6.1.1 on 2026-09-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_remove_mediaasset_alt_text_remove_mediaasset_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelanguage',
            name='home_page',
            field=models.ForeignKey(blank=True, help_text='Sprachunabhängige Seite, die für diese Website-Sprache als Startseite verwendet wird.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_for_site_languages', to='cms.page', verbose_name='Startseite'),
        ),
    ]
