# Generated by Django 6.1.1 on 2026-09-18 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_sitelanguage_home_page'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pagetranslation',
            name='unique_page_translation_slug_per_site_language',
        ),
    ]
